# IP webcams
#   - platform: ffmpeg
#     name: vlcCamera
#     input: -rtsp_transport tcp -i rtsp://192.168.1.222:8554/av_stream/ch0

#   - platform: ffmpeg
#     name: Sonoff camera
#     input: -rtsp_transport tcp -i rtsp://rtsp:12345678@192.168.43.117:554/av_stream/ch0
- platform: generic
  name: ISS
  still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }}&zoom=4&size=865x512&maptype=mapnik&markers={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }},lightblue
  limit_refetch_to_url_change: true
