title: Hosts
icon: mdi:network

type: custom:layout-card
layout_type: custom:masonry-layout
layout:
  width: 500

cards:
  - type: 'custom:config-template-card'
    variables:
      - states['sensor.hostnames'].state
      - ''' DHCP clients as of '''
      - states['sensor.hostnames'].attributes.lastUpdated
    entities:
      - sensor.hostnames
    card:
      type: custom:list-card
      entity: sensor.hostnames
      title: '${ vars[0] + vars[1] + vars[2] }'
      feed_attribute: hosts
      columns:
        - title: Hostname
          field: field4
        - title: IP Address
          field: field3
          style:
            - text-align: center
        - title: MAC Address
          field: field2
          style:
            - text-align: center


  - type: 'custom:config-template-card'
    variables:
      - states['sensor.hostnames_spiti'].state
      - ''' Network Hosts as of '''
      - states['sensor.hostnames_spiti'].attributes.lastUpdated
    entities:
      - sensor.hostnames_spiti
    card:
      type: custom:list-card
      entity: sensor.hostnames_spiti
      title: '${ vars[0] + vars[1] + vars[2] }'
      feed_attribute: hosts
      columns:
        - title: Hostname
          field: HostName
        - title: IP Address
          field: IPAddress
          style:
            - text-align: center
