#########################################################################################
# Backup
#########################################################################################
- alias: '[System] - Make weekly Hassio backup'
  trigger:
    - platform: time
      at: '23:45:00'
  condition:
    - condition: time
      weekday:
        - fri
  action:
    - service: hassio.backup_full
      data_template:
        name: Automated backup {{ now().strftime('%Y-%m-%d') }} running HA version {{ states('sensor.current_version') }}
    - service: notify.telegram_viktor
      data_template:
        title: Scheduled Hass.io backup
        message: Backup {{ now().strftime('%Y-%m-%d') }} running HA version {{ states('sensor.current_version')}} is being generated.


