#########################################################################################
# Viktor's office
#########################################################################################

- alias: "Start timer when boiler is started - viktor's office"
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.office_boiler_timer_duration
    above: 0
  action:
  - service: timer.start
    data_template:
      entity_id: timer.boiler_viktors_office
      duration: "00:{{ states('sensor.office_boiler_timer_duration') | int }}:00"


- alias: "Stop timer when boiler is switched off - viktor's office"
  trigger:
    platform: state
    entity_id:
      - switch.office_boiler
    to: "off"
  action:
  - service: timer.cancel
    data:
      entity_id: timer.boiler_viktors_office
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: sensor.office_boiler_timer_duration
      state: 0

