#########################################################################################
# Global Disaster Alert and Coordination System (GDACS)
#########################################################################################
- alias: 'GDACS happened'
  trigger:
    - platform: geo_location
      source: gdacs
      zone: zone.home
      event: enter
  action:
    - service: notify.telegram_viktor
      data_template:
        title: Disaster Alert
        message: "{{ trigger.to_state.name }} - {{ trigger.to_state.attributes.status }}"
    - service: notify.telegram_victoria
      data_template:
        title: Disaster Alert
        message: "{{ trigger.to_state.name }} - {{ trigger.to_state.attributes.status }}"

    - service: persistent_notification.create
      data_template:
        message: "{{ trigger.to_state.name }} - {{ trigger.to_state.attributes.status }}"
        title: "Disaster Alert"

