#########################################################################################
# Viktor's office
#########################################################################################

- alias: "Switch off office AC after an hour"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hvac_viktors_office
  action:
    - service: script.viktors_office_ac_off


        