#########################################################################################
# meteoalarm
#########################################################################################
- alias: 'Bad weather alert - meteoalarm.eu - Attika'
  trigger:
    - platform: state
      entity_id: binary_sensor.meteoalarm
      attribute: message_id
  condition:
  - condition: state
    entity_id: binary_sensor.meteoalarm
    state: 'on'
  action:
    - service: notify.telegram_viktor
      data_template:
        title: "MeteoAlarm: {{ state_attr('binary_sensor.meteoalarm', 'awareness_type') }} ({{ state_attr('binary_sensor.meteoalarm', 'awareness_level') }})"
        message: "{{ state_attr('binary_sensor.meteoalarm', 'message') }} Effective from {{ state_attr('binary_sensor.meteoalarm', 'from') }} until {{ state_attr('binary_sensor.meteoalarm', 'until') }}" 

    - service: notify.telegram_victoria
      data_template:
        title: "MeteoAlarm: {{ state_attr('binary_sensor.meteoalarm', 'awareness_type') }} ({{ state_attr('binary_sensor.meteoalarm', 'awareness_level') }})"
        message: "{{ state_attr('binary_sensor.meteoalarm', 'message') }} Effective from {{ state_attr('binary_sensor.meteoalarm', 'from') }} until {{ state_attr('binary_sensor.meteoalarm', 'until') }}" 

         

