#########################################################################################
# Themse
#########################################################################################

- alias: "Light theme after Sunrise"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: frontend.set_theme
      data:
        # name: ios-light-mode-dark-blue-alternative
        name: "kibibit"

- alias: 'Light theme after reboot in day'
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    service: frontend.set_theme
    data:
      # name: ios-light-mode-dark-blue-alternative
      name: "kibibit"

      
- alias: "Dark theme after Sunset"
  trigger:
    platform: sun
    event: sunset
  action:
    - service: frontend.set_theme
      data:
        # name: ios-dark-mode-dark-blue-alternative
        name: "kibibit-dark-cards"

- alias: 'Dark theme after reboot in night'
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: frontend.set_theme
    data:
      # name: ios-dark-mode-dark-blue-alternative
      name: "kibibit-dark-cards"













# - alias: "Light theme after Sunrise"
#   trigger:
#     platform: sun
#     event: sunrise
#   action:
#     - service: frontend.set_theme
#       data:
#         # name: ios-light-mode-dark-blue-alternative
#         name: "iOS Light Mode"

# - alias: 'Light theme after reboot in day'
#   trigger:
#     platform: homeassistant
#     event: start
#   condition:
#     - condition: state
#       entity_id: sun.sun
#       state: 'above_horizon'
#   action:
#     service: frontend.set_theme
#     data:
#       # name: ios-light-mode-dark-blue-alternative
#       name: "iOS Light Mode"

      
# - alias: "Dark theme after Sunset"
#   trigger:
#     platform: sun
#     event: sunset
#   action:
#     - service: frontend.set_theme
#       data:
#         # name: ios-dark-mode-dark-blue-alternative
#         name: "iOS Dark Mode"

# - alias: 'Dark theme after reboot in night'
#   trigger:
#     platform: homeassistant
#     event: start
#   condition:
#     condition: state
#     entity_id: sun.sun
#     state: 'below_horizon'
#   action:
#     service: frontend.set_theme
#     data:
#       # name: ios-dark-mode-dark-blue-alternative
#       name: "iOS Dark Mode"


