#########################################################################################
# Home Assistant update is available
#########################################################################################
- alias: Check configuration against the new update
  description: Starts the check config addon when an update becomes available
  trigger:
    - platform: state
      entity_id: update.home_assistant_core_update
      #entity_id: binary_sensor.core_updated
      to: "on"
  condition: []
  action:
    service: hassio.addon_start
    data:
      addon: core_check_config
